server:
  port: 8085

spring:
  application:
    name: backend

camunda:
  client:
    mode: self-managed
    auth:
      method: none
    grpc-address: ${CAMUNDA_GRPC_ADDRESS:http://localhost:26500}
    rest-address: ${CAMUNDA_REST_ADDRESS:http://localhost:8080}
